// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Periferico.Models;

namespace Periferico.Migrations
{
    [DbContext(typeof(APIDBContext))]
    [Migration("20201119153244_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Periferico.Models.E270ConAse", b =>
                {
                    b.Property<string>("noContratante")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("beMaxInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAplicativoTx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coCalservicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coEspecialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coInProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coParentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSuTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noMaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuAutOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiCaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txRequest")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("noContratante");

                    b.ToTable("E270ConAse");
                });

            modelBuilder.Entity("Periferico.Models.E270ConAseAcc", b =>
                {
                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("beMaxInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAplicativoTx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coCalservicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coEspecialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coInProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coParentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSuTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noMaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuAutOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiCaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txRequest")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("noTransaccion");

                    b.ToTable("E270ConAseAcc");
                });

            modelBuilder.Entity("Periferico.Models.E271ConCod", b =>
                {
                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coEsPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coMoneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coParentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiPoliza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esMarital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinVigencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feIniVigencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feInsTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feUpFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noMaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noMaTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuContratoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuIdenPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPoliza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuSoBeneficio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soBeneficio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiCaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiPlanSalud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRemitente");

                    b.ToTable("E271ConCod");
                });

            modelBuilder.Entity("Periferico.Models.E271ConCodDetalle", b =>
                {
                    b.Property<string>("idProducto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271ConCodidRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("beMaxInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("canCalServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("canServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coCalServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coInRestriccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coPagoFijo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coPagoVariable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSubTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiMoneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deflagCaGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinCarencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinEspera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flagCaGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("infBeneficio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgConEspeciales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProducto");

                    b.HasIndex("E271ConCodidRemitente");

                    b.ToTable("E271ConCodDetalle");
                });

            modelBuilder.Entity("Periferico.Models.E271ConDtad", b =>
                {
                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaCalificador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaNoEmCalificador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coUbigeoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deDirPaciente1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deDirPaciente2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noEmCalificador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuTeContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiCaCalificador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idReceptor");

                    b.ToTable("E271ConDtad");
                });

            modelBuilder.Entity("Periferico.Models.E271ConMed", b =>
                {
                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRemitente");

                    b.ToTable("E271ConMed");
                });

            modelBuilder.Entity("Periferico.Models.E271ConMedDetalle", b =>
                {
                    b.Property<string>("idFuenteRE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271ConMedidRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("coRestriccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSeCIE10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dePreexistencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moDiagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgObsPr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiEspera")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idFuenteRE");

                    b.HasIndex("E271ConMedidRemitente");

                    b.ToTable("E271ConMedDetalle");
                });

            modelBuilder.Entity("Periferico.Models.E271ConNom", b =>
                {
                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRemitente");

                    b.ToTable("E271ConNom");
                });

            modelBuilder.Entity("Periferico.Models.E271ConNomDetalle", b =>
                {
                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271ConNomidRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coEsPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coParentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esMarital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noMaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuContratoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuSCTR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiCaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("noPaciente");

                    b.HasIndex("E271ConNomidRemitente");

                    b.ToTable("E271ConNomDetalle");
                });

            modelBuilder.Entity("Periferico.Models.E271ConObs", b =>
                {
                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSubCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teMsgLibre1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teMsgLibre2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRemitente");

                    b.ToTable("E271ConObs");
                });

            modelBuilder.Entity("Periferico.Models.E271ConProc", b =>
                {
                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTransaccion");

                    b.ToTable("E271ConProc");
                });

            modelBuilder.Entity("Periferico.Models.E271ConProcDetalle", b =>
                {
                    b.Property<string>("idFuentePE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271ConProcidTransaccion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("coExCarencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coInProcedimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coInRestriccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coProcedimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiEspera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deExCarencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deTiEspera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinVigencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idFuenteEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idFuenteTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imDeducible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuFrecuencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("poCuExDecimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teMsgExCarencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teMsgObservacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teMsgTiEspera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiNuDias")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idFuentePE");

                    b.HasIndex("E271ConProcidTransaccion");

                    b.ToTable("E271ConProcDetalle");
                });

            modelBuilder.Entity("Periferico.Models.E271ResCg", b =>
                {
                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRemitente");

                    b.ToTable("E271ResCg");
                });

            modelBuilder.Entity("Periferico.Models.E271ResCgDetalle", b =>
                {
                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271ResCgidRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coMoneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coProcedimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deProcedimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCaReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noMaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCaReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuSoCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiCaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiPlanSalud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("veCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("noPaciente");

                    b.HasIndex("E271ResCgidRemitente");

                    b.ToTable("E271ResCgDetalle");
                });

            modelBuilder.Entity("Periferico.Models.E271ResDeriva", b =>
                {
                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idReceptor");

                    b.ToTable("E271ResDeriva");
                });

            modelBuilder.Entity("Periferico.Models.E271ResDerivaDetalle", b =>
                {
                    b.Property<string>("idCaReferencia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271ResDerivaidReceptor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coLuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coParentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSubTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feAtSalud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noLuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoTrabajoAfiliado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reIdContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teMsgLibre1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoTrabajoAfiliado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCaReferencia");

                    b.HasIndex("E271ResDerivaidReceptor");

                    b.ToTable("E271ResDerivaDetalle");
                });

            modelBuilder.Entity("Periferico.Models.E271ResSctr", b =>
                {
                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDocPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRemitente");

                    b.ToTable("E271ResSctr");
                });

            modelBuilder.Entity("Periferico.Models.E271ResSctrDetalle", b =>
                {
                    b.Property<string>("idCaReContratante")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271ResSctridRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("coEmContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coEmReLuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coLuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deTiAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feAfiliacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feOcAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCaReLuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noEmApPaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noEmLuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reIdContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reIdLuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiCaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiCaLuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCaReContratante");

                    b.HasIndex("E271ResSctridRemitente");

                    b.ToTable("E271ResSctrDetalle");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAut", b =>
                {
                    b.Property<string>("noMaTitular")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("beMaxInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("canCalServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("canServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAdmisionista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coAfTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coCalServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coEsPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coEspecialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coMoneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coPagoFijo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coPagoVariable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coPaisRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coParentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSubTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiMoneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiPolizaAfiliacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deProductoDeFarmacia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deTiAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deflagCG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esMarital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feAfiliacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinCarencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinEspera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinVigencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feIncTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feIniVigencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feNaRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feOcuAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flagCG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("geRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idDeProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idDerFarmacia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idInfAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgConEspeciales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgConEspecialesPre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgObsPre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noMaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noMaRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCobPreExistencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuContratoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDecAccidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuIdenEmpleador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPoliza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuSoBeneficio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("obsCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soBeneficio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoRegafi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiPlanSalud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiProducto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("noMaTitular");

                    b.ToTable("E271SolAut");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAutDetalleExeCar", b =>
                {
                    b.Property<string>("idExCarencia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271SolAutnoMaTitular")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("coExCarencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deExCarencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgExCarencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idExCarencia");

                    b.HasIndex("E271SolAutnoMaTitular");

                    b.ToTable("E271SolAutDetalleExeCar");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAutDetalleProEsp", b =>
                {
                    b.Property<string>("coTiProConAmbulatoria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271SolAutnoMaTitular")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("caConAmbulatoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coInProcedimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("frConAmbulatoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("geConAmbulatoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imDeducible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgConAmbulatoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuPlanConAmbulatoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("poConAmbulatoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("coTiProConAmbulatoria");

                    b.HasIndex("E271SolAutnoMaTitular");

                    b.ToTable("E271SolAutDetalleProEsp");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAutDetalleRes", b =>
                {
                    b.Property<string>("idRestricciones")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CIE10Restricciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E271SolAutnoMaTitular")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("deRestricciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinEsperaRestricciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monTopeRestricciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgRestricciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("obsRestricciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRestricciones");

                    b.HasIndex("E271SolAutnoMaTitular");

                    b.ToTable("E271SolAutDetalleRes");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAutDetalleTieEsp", b =>
                {
                    b.Property<string>("idTiEspera")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("E271SolAutnoMaTitular")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("coTiEspera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deTiEspera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feFinVigenciaTiEspera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgTiEspera")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTiEspera");

                    b.HasIndex("E271SolAutnoMaTitular");

                    b.ToTable("E271SolAutDetalleTieEsp");
                });

            modelBuilder.Entity("Periferico.Models.E278ContEntVinc", b =>
                {
                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("caIPRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noIPRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuRucIPRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiDoIPRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idReceptor");

                    b.ToTable("E278ContEntVinc");
                });

            modelBuilder.Entity("Periferico.Models.E278ResEntVinc", b =>
                {
                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msgRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRemitente");

                    b.ToTable("E278ResEntVinc");
                });

            modelBuilder.Entity("Periferico.Models.E278SolCg", b =>
                {
                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apMaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("caPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coTiDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuDoPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuSoCarGarantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiFinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCorrelativo");

                    b.ToTable("E278SolCg");
                });

            modelBuilder.Entity("Periferico.Models.E997ResAut", b =>
                {
                    b.Property<string>("idReceptor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("coError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCorrelativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idRemitente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inCoErrorEncontrado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuAutorizacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idReceptor");

                    b.ToTable("E997ResAut");
                });

            modelBuilder.Entity("Periferico.Models.E271ConCodDetalle", b =>
                {
                    b.HasOne("Periferico.Models.E271ConCod", null)
                        .WithMany("listDetalle")
                        .HasForeignKey("E271ConCodidRemitente");
                });

            modelBuilder.Entity("Periferico.Models.E271ConMedDetalle", b =>
                {
                    b.HasOne("Periferico.Models.E271ConMed", null)
                        .WithMany("listDetalleResponse")
                        .HasForeignKey("E271ConMedidRemitente");
                });

            modelBuilder.Entity("Periferico.Models.E271ConNomDetalle", b =>
                {
                    b.HasOne("Periferico.Models.E271ConNom", null)
                        .WithMany("listDetalleResponse")
                        .HasForeignKey("E271ConNomidRemitente");
                });

            modelBuilder.Entity("Periferico.Models.E271ConProcDetalle", b =>
                {
                    b.HasOne("Periferico.Models.E271ConProc", null)
                        .WithMany("listaDetalleResponse")
                        .HasForeignKey("E271ConProcidTransaccion");
                });

            modelBuilder.Entity("Periferico.Models.E271ResCgDetalle", b =>
                {
                    b.HasOne("Periferico.Models.E271ResCg", null)
                        .WithMany("listaDetalleResponse")
                        .HasForeignKey("E271ResCgidRemitente");
                });

            modelBuilder.Entity("Periferico.Models.E271ResDerivaDetalle", b =>
                {
                    b.HasOne("Periferico.Models.E271ResDeriva", null)
                        .WithMany("listDetalleResponse")
                        .HasForeignKey("E271ResDerivaidReceptor");
                });

            modelBuilder.Entity("Periferico.Models.E271ResSctrDetalle", b =>
                {
                    b.HasOne("Periferico.Models.E271ResSctr", null)
                        .WithMany("listDetalleResponse")
                        .HasForeignKey("E271ResSctridRemitente");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAutDetalleExeCar", b =>
                {
                    b.HasOne("Periferico.Models.E271SolAut", null)
                        .WithMany("listDetalleExeCar")
                        .HasForeignKey("E271SolAutnoMaTitular");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAutDetalleProEsp", b =>
                {
                    b.HasOne("Periferico.Models.E271SolAut", null)
                        .WithMany("listDetalleProEsp")
                        .HasForeignKey("E271SolAutnoMaTitular");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAutDetalleRes", b =>
                {
                    b.HasOne("Periferico.Models.E271SolAut", null)
                        .WithMany("listDetalleRes")
                        .HasForeignKey("E271SolAutnoMaTitular");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAutDetalleTieEsp", b =>
                {
                    b.HasOne("Periferico.Models.E271SolAut", null)
                        .WithMany("listDetalleTieEsp")
                        .HasForeignKey("E271SolAutnoMaTitular");
                });

            modelBuilder.Entity("Periferico.Models.E271ConCod", b =>
                {
                    b.Navigation("listDetalle");
                });

            modelBuilder.Entity("Periferico.Models.E271ConMed", b =>
                {
                    b.Navigation("listDetalleResponse");
                });

            modelBuilder.Entity("Periferico.Models.E271ConNom", b =>
                {
                    b.Navigation("listDetalleResponse");
                });

            modelBuilder.Entity("Periferico.Models.E271ConProc", b =>
                {
                    b.Navigation("listaDetalleResponse");
                });

            modelBuilder.Entity("Periferico.Models.E271ResCg", b =>
                {
                    b.Navigation("listaDetalleResponse");
                });

            modelBuilder.Entity("Periferico.Models.E271ResDeriva", b =>
                {
                    b.Navigation("listDetalleResponse");
                });

            modelBuilder.Entity("Periferico.Models.E271ResSctr", b =>
                {
                    b.Navigation("listDetalleResponse");
                });

            modelBuilder.Entity("Periferico.Models.E271SolAut", b =>
                {
                    b.Navigation("listDetalleExeCar");

                    b.Navigation("listDetalleProEsp");

                    b.Navigation("listDetalleRes");

                    b.Navigation("listDetalleTieEsp");
                });
#pragma warning restore 612, 618
        }
    }
}
